### ISSUE TITLE
Error in URL  %!(EXTRA string=

### ISSUE THREAD

**Issue by so121183gak** [de-don/sftp_uploader#10]
Hello, I'm trying to use this script to send screenshots via SFTP. But there is a problem, when it generates a URL for me, it will turn out like this:
http://2w2.more.er:3333/~ivanov%!(EXTRA string=_OPbI.png)

1. How to make url without it  %!(EXTRA string=
2. How can I add a full date to the beginning of a filename _OPbI.png

System: 5.4.0-135-generic #152-Ubuntu 20.04
GO:  version go1.13.8

**Comment by de-don** [comment]
Could you please provide your configuration (without sensitive data)?

**Comment by so121183gak** [comment]
here is the contents of the config.ini file

```
[server]
host = 2w2.more.er
port = 2033

[credentials]
username = ivanov
password = my_pass

[other]
# for example 2006-01-02 15:04:05 (USE ONLY THIS VALUE OF DATE)
# 2006-01-02_15-04-05
# 15h04m05s_2006y01m02d
#name_pattern = screen_2006-01-02_15-04-05
upload_directory = /home/www
url_pattern = http://2w2.more.er:3333/~ivanov
```

**Comment by de-don** [comment]
@so121183gak try to change url_pattern to this:
```
url_pattern = "http://2w2.more.er:3333/~ivanov/%s"

**Comment by so121183gak** [comment]
> @so121183gak try to change url_pattern to this:
> 
> ```
> url_pattern = "http://2w2.more.er:3333/~ivanov/%s"
> ```
Thanks it worked for me
