### ISSUE TITLE
Pre-Built Binaries are not Up to Date 

### ISSUE THREAD

**Issue by adityaxdiwakar** [de-don/sftp_uploader#7]
The released binaries and the actual code is not the same. As a result, when I was trying to use these distributed binaries to setup a custom URL path, it was not being registered.

I would fix this myself but I cannot edit releases (obviously), so this is just an FYI! Might be helpful for new users.

**Comment by de-don** [comment]
Thanks, I have pushed a new release!
https://github.com/de-don/sftp_uploader/releases/tag/v1.2
