### ISSUE TITLE
doesn't work on pterodactyl servers

### ISSUE THREAD

**Issue by Robin-Sch** [de-don/sftp_uploader#8]
Hello, I use a pterodactyl server from my friend, but it doesn't work.
When I get the URL copied to my clipboard, it's wrong (http://domain.com/sftp_username/screenxxx.png), but it should be http://domain.com:3000/screenxxx.png. 
And I would like to have it uploaded in a specific directory, but that doesn't work, it always uploads it in the root directory.

My configuration is:
```
[server]
host = domain.com
port = 2022 # (sftp port)

[credentials]
username = sftp_username
password = sftp_password

[other]
# for example 2006-01-02 15:04:05 (USE ONLY THIS VALUE OF DATE)
# 2006-01-02_15-04-05
# 15h04m05s_2006y01m02d
name_pattern = "screen_2006-01-02_15-04-05"
upload_directory = /home/container/uploads
url_pattern = "http://domain.com:3000/%s"
```

**Comment by de-don** [comment]
Hi, @RobinSchapendonk, Last binaries looks like not actual. I will build new version and make a new release now.

**Comment by de-don** [comment]
@RobinSchapendonk , try to use the latest version:
https://github.com/de-don/sftp_uploader/releases/tag/v1.2
